### ISSUE TITLE
Defining configuration outside of the ActiveRecord model

### ISSUE THREAD

**Issue by tboyko** [comma-csv/comma#101]
Does comma have pre-existing support for defining the comma config outside of the ActiveRecord model? For instance, is there an easy way to create an `app/serializers` folder for this config? I'd prefer to keep it separate if possible, and want to avoid using an `include` if there's already a way to do this.

Thanks!

**Comment by eitoball** [comment]
No. Interesting idea. May I ask why would you do so?　

You could do by monkey patching `to_comma` method. Maybe like...

```ruby
module Simple
  def self.included(m)
    m.comma :simple do
      name
      desrciption
    end
  end
end

module DynamicCommaDefinition
  def to_comma(style = :default)
     self.class.include(style.to_s.constantize)
  ensure
    super
  end
end
Object.prepend(DynamicCommaDefinition)
```

**Comment by tboyko** [comment]
The purpose would be to keep the active record model class lean. It's a
habit I've developed from using gems like Draper:
https://github.com/drapergem/draper

**Comment by eitoball** [comment]
> The purpose would be to keep the active record model class lean.

I see. Thank you.
