### ISSUE TITLE
data formatting methods not called.

### ISSUE THREAD

**Issue by Mziserman** [comma-csv/comma#106]
Hello,

I am trying to use a data formatting method across many columns. It looks like that : 

```
def humanize_boolean(boolean)
  unless boolean.nil?
    I18n.t boolean ? 'global.yes' : 'global.no'
  end
end
```

But when I call it in the comma definition :

```
comma do
  id Event.human_attribute_name('id')
  name Event.human_attribute_name('name')
  activated Event.human_attribute_name('activated') do |boolean|
    humanize_boolean(boolean)
  end
end
```

I get a runtime error "Unknown data symbol false" (it can be Unknown data symbol true to, and same thing for integers).

What's odd to me is that if I put the body of humanize_boolean inside of the comma block everything works as intended.

```
comma do
  id Event.human_attribute_name('id')
  name Event.human_attribute_name('name')
  activated Event.human_attribute_name('activated') do |boolean|
    unless boolean.nil?
      I18n.t boolean ? 'global.yes' : 'global.no'
    end
  end
end
```

Am I doing something wrong ?

**Comment by eitoball** [comment]
How do you define `humanize_boolean` method? It should be defined as **class** method like

```ruby
class Event < ActiveRecord::Base
  class << self
    def humavize_boolean(boolean)
       ...
    end
  end
end
```
