### ISSUE TITLE
Translating boolean values

### ISSUE THREAD

**Issue by jmuheim** [comma-csv/comma#108]
I have the following `to_comma` method:

```ruby
  comma do
    critical Finding.human_attribute_name :critical # bool
    closed Finding.human_attribute_name :closed # bool
  end
```

This results in `true` and `false` items for both `critical` and `closed`:

```
Critical? | Closed?
----------|--------
true      | false
false     | true
false     | false
```

I'd rather have the name of the attribute instead of `true` and empty instead of `false`:

```
Critical? | Closed?
----------|--------
Critical  |
          | Closed
          |
```

Or maybe:

```
Critical?    | Closed?
-------------|--------
Critical     | Not Closed
Not Critical | Closed
Not Critical | Not Closed
```

I can't find a way to do that in the `comma` method. Do I miss something?

**Comment by eitoball** [comment]
You could use block. When you supply a block, comma will yield attribute value that you specified. For example,  for `critical` attribute in your description.

```ruby
comma do
  critical 'Critical?' do |c| c ? Finding.human_attribute_name(:critical) : '' end
end
```

In the example above, `do...end` is used because of operator precedence. If you want to use `{...}`, you might need to add `()`.

**Comment by jmuheim** [comment]
Thank you.
