### ISSUE TITLE
Using comma with padrino ruby framework

### ISSUE THREAD

**Issue by wakatara** [comma-csv/comma#138]
I'm currently upgrading a 10 year old padrino app (upgraded before 4 years ago) to padrino 0.15.2 - a sinatra and AR based framework. I'd like to use `comma` for csv exports (to replace MS deprecated openxml xls formats that are now broken :-/ ). 

Because `comma` hooks into AR, I was hoping I could use it like so: 

```ruby
  # admin/controllers/reports.rb
  get :species_data_dump, :provides => :csv do
    @species = Species.order(:name)

    render csv: @species
  end
```

Perhaps predictably, I'm getting an error in that it's not expecting an instance variable here, but I imagine that's because I don't know comma internals well enough. Is there a way to hook into the rails magic you built somewhat easily?

**Comment by eitoball** [comment]
@wakatara

> I'm getting an error in that it's not expecting an instance variable here

Can you show me this error? What version of ActiveRecord are you using, and how is it required?

**Comment by eitoball** [comment]
I am closing this issue for now. Please re-open if you can show me error.
