### ISSUE TITLE
Comma uses wrong comma block on single table inheritance in Rails

### ISSUE THREAD

**Issue by chrisdb** [comma-csv/comma#89]
If a comma block is defined on a super class, but missing in one sub class, the comma block from a wrong subclass is used, instead of the one from the super class.
This behaviour only occurs in a Rails / Active Record environment and is not a general inheritance problem.
To reproduce, execute the tests I added in this commit:
https://github.com/chrisdb/comma/commit/508c15961533544ee766af748faefdb203616235

**Comment by bvogel** [comment]
Any chance to get this fixed?

**Comment by eitoball** [comment]
Fixed and released version 3.2.3.

Thank you for reporting and specs.

**Comment by bvogel** [comment]
Thanks for fixing!

**Comment by bvogel** [comment]
Hmm - sorry to bother but the fix breaks existing code for me. 
We have three classes: Customer, which is the parent, Buyer and Seller. Buyer and Seller inherit from Customer. Within Customer we define two comma blocks, one without scope and one with scope :newsletter. Before the patch I could call `some_sellers_list.to_comma(style: :newsletter)` and that would in turn call the parent class implementation. Now I get an error `No comma format for class Seller defined for style newsletter` - Did you test the specs @chrisdb provided?

**Comment by eitoball** [comment]
@bvogel can you try https://github.com/eitoball/comma/commit/36eabb5f3dad8bcbffccb0c65bfe015ef1ab259e and check if spec in this change cover your case?

**Comment by bvogel** [comment]
@eitoball that version seems to do the trick. Thanks for looking into this.

**Comment by eitoball** [comment]
Released version 3.2.4. Thx for reporting.
