### ISSUE TITLE
Umlauts correct in CSV file, but Excel misinterprets them. Can I tell Excel the format?

### ISSUE THREAD

**Issue by jmuheim** [comma-csv/comma#95]
My exported CSV has umlauts (ä, ö, etc.). When I open the exported file in my text editor, it's displayed correctly, but in MS Excel (Mac), it looks like this: `Ã¤` instead of `ä`, etc.

Is there a way to tell Excel the correct format (I guess it's UTF-8)?

**Comment by tommeier** [comment]
I'm afraid not, http://answers.microsoft.com/en-us/mac/forum/macoffice2016-macexcel/does-excel-2016-for-mac-support-utf-8-csv-imports/4576cfb2-4e23-442d-a487-2f9adaa78f72

Not as far as I'm aware anyway. You could potentially export the csv, then change the file encoding to an Excel friendly encoding then open in Excel.

**Comment by jmuheim** [comment]
Okay, thank you.
